language: haskell
install: cabal install  --enable-tests --enable-benchmarks --only-dependencies
script: cabal configure --enable-tests --enable-benchmarks && cabal build && cabal test && cabal bench
